### ISSUE TITLE
preliminary community infrastructure action plan

### ISSUE THREAD

**Issue by NavyaNelluri** [chintakjoshi/TWA-OSS#66] opened 2023-08-06 02:57 UTC
**Identify Community Objectives/TASK:**

Providing employment opportunities and career development for individuals with criminal records.

**Infrastructure Requirements:**

Establishing a website or online platform to serve as the central hub for the Transform Workforce Academy community.

**Community Assessment:**

1. Conduct ing surveys or interviews with individuals with criminal records to understand their specific needs and barriers to employment.
 Examples: the surveys can be through the online google forms.
2. Engaging with employers to determine their willingness to hire individuals with criminal records and identify potential industries for job placements.

**Team and Roles:**

1. We should divide a team who can assign the bug./enhancement in the project to the specific core developer of that respective code.
2. QA testing team
3. Final deployment team after the approval.
 - Includes end to end deployement for production live.
4. One specific team for continous monitoring/support in the live environment.

**Comment by harjothkaur** [comment] 2023-08-06 04:01
Adding some more points to the above action plan,

**Community Objectives/TASK:**

1. Providing employment opportunities and career development for individuals with criminal records.
2. Facilitating skill development and training programs tailored to the needs of individuals with criminal records.
3. Encouraging and supporting employers to implement inclusive hiring practices that consider individuals with criminal records.

**Infrastructure Requirements:**

1. Establishing a user-friendly and accessible website or online platform for the Transform Workforce Academy community.
2. Implementing secure login and authentication features to protect user data and maintain privacy.
3. Creating a centralized database to store user information, survey responses, and employer details.
4. Ensuring scalability and flexibility of the platform to accommodate future growth and updates.

**Community Assessment:**

1. Analyzing survey results or conducting interviews with individuals with criminal records to gain insights into their unique challenges, preferences, and aspirations regarding employment.
2. Identifying the most common barriers faced by individuals with criminal records when seeking employment, such as stigmatization and limited access to opportunities.
3. Assessing the level of support and willingness from employers to hire individuals with criminal records and understanding their concerns or reservations.

**Team and Roles:**

1. Web Developers: Responsible for building and maintaining the website or online platform.
2. UX/UI Designers: Ensuring the platform's user interface is intuitive and user-friendly.
3. Database Administrators: Managing the centralized database, ensuring data integrity and security.
4. Skill Development Instructors: Designing and conducting training programs for individuals with criminal records to enhance their employability.
5. Quality Assurance (QA) Testers: Thoroughly testing the platform to identify and fix any bugs or issues before deployment.
6. Deployment Team: Responsible for the final deployment of the platform to the production environment.
7. Support Team: Providing continuous monitoring and support in the live environment to address any technical or user-related concerns.

**Implementation Plan:**

1. Conduct preliminary research and gather resources to understand the scope and requirements of the project.
2. Form the project team, assign roles and responsibilities, and establish clear communication channels.
3. Design and develop the website or online platform with a focus on user experience and accessibility.
4. Conduct thorough testing and debugging of the platform before deploying it to the live environment.
5. Launch the Transform Workforce Academy platform and continuously monitor its performance and user feedback.
6. Provide ongoing support and updates to enhance the platform's functionality and meet the evolving needs of the community.

**Monitoring and Evaluation:**

1. Track the number of individuals with criminal records who secure employment opportunities through the platform.
2. Conduct periodic assessments to evaluate the overall effectiveness and success of the initiative in achieving its community objectives.

**Sustainability:**

1. Explore potential funding opportunities, grants, or sponsorships to support the long-term sustainability of the Transform Workforce Academy.

**Comment by Shirisha777** [comment] 2023-08-06 04:28
**Community Objectives/TASK:** 

1, supplying those with criminal records with employment possibilities and career growth.
2, Encouraging and assisting firms to adopt inclusive hiring procedures that take people with criminal backgrounds into account.

**Infrastructure Requirements:**

1, Creating a website or online platform that will act as the community's main hub for the Transform Workforce Academy.
2, Putting in place secure login and authentication measures to safeguard user information and uphold privacy.
Community Assessment:
1, conducting surveys or interviews with people who have had prior arrests to identify their unique needs and job challenges.
2, Examples include surveys that can be completed online using Google forms.
3, Interacting with employers to find out if they're prepared to recruit someone with a criminal record and identifying potential employment sectors.

**Team and Roles:**

Team and Roles: Team for Bug/Enhancement Assignment: This team is in charge of managing and allocating bugs or improvements in the project to certain core developers who can take the necessary action to fix them. The team will track and prioritize concerns using a project management tool like Jira to make sure they are effectively fixed. https://www.atlassian.com/software/jira.

Team for Quality Assurance (QA) Testing: The QA testing team is in charge of extensively testing the website or online platform to make sure it works as intended and satisfies community demands. Any defects or problems will be found and reported, and the core developers will fix them. To expedite the process, the team will employ testing technologies like Selenium for automated testing. (Link: https://www.selenium.dev/; Selenium)

Team in charge of final deployment: After the website or platform has been approved and put through testing, this team will manage the final deployment. They will make sure that the deployment procedure is easy and seamless, enabling users to access the community platform. To bundle and distribute the program reliably across environments, the team will use deployment tools like Docker. Docker can be accessed at https://www.docker.com.

Team for Continuous Monitoring and Support: This team is in charge of continuously keeping an eye on the live environment and offering assistance to users and the community. They will take care of any post-deployment problems, carry out routine maintenance, and guarantee the availability and dependability of the platform. The team will track performance and look for any issues using monitoring technologies like Prometheus and Grafana. (Links: Grafana, https://grafana.com/; Prometheus, https://prometheus.io)

**Concrete Plan of Action:**

Conduct a Community Needs Assessment:
The project team will start by conducting surveys and interviews with individuals with criminal records to understand their specific needs and challenges related to employment. This information will help in tailoring the platform's features and services to meet their requirements effectively.

Engage with Potential Employers:
The team will reach out to employers to gauge their willingness to hire individuals with criminal records and identify industries or sectors that are open to providing job opportunities. Building strong partnerships with these employers will increase the chances of successful job placements for the community members.

Design and Develop the Central Hub:
Based on the assessment results and employer engagements, the team will design and develop the Transform Workforce Academy community platform. They will ensure that the website offers user-friendly interfaces, facilitates job matching, and provides resources for career development.

Implement Agile Bug/Enhancement Workflow:
The bug/enhancement assignment team will follow an Agile workflow using a project management tool like Jira. They will categorize and prioritize issues, ensuring that the core developers can efficiently address them based on their expertise and availability.

Set Up Automated Testing:
The QA testing team will implement automated testing using tools like Selenium. This will enable quick and comprehensive testing, identifying and resolving issues before deployment, and ensuring a stable platform for the community.

Prepare for Deployment:
The final deployment team will use Docker to package the application and ensure a smooth deployment process. They will set up monitoring tools like Prometheus and Grafana to track performance metrics during deployment and after going live.

Establish Continuous Support:
The continuous monitoring/support team will be ready to address any issues or support requests from users in the live environment. They will regularly monitor the platform's performance and make improvements as needed to ensure a seamless experience for the community.

**Link or Citation Justifying the Suggestion:**

The Agile bug/enhancement workflow using Jira is a widely adopted and proven approach for managing software development projects efficiently. (Link: https://www.atlassian.com/agile/project-management/epics-stories-themes)

Automated testing with Selenium is a standard practice in modern software development, providing faster and more reliable testing results. (Link: https://www.selenium.dev/documentation/en/getting_started/)

Using Docker for deployment ensures consistent and repeatable deployment processes, reducing the chances of deployment-related issues. (Link: https://www.docker.com/why-docker)

Monitoring tools like Prometheus and Grafana help maintain the health and performance of the platform, allowing proactive measures to prevent potential problems. (Links: https://prometheus.io/docs/introduction/overview/ , https://grafana.com/docs/grafana/latest/features/datasources/prometheus/)

By following these strategies and implementing the suggested tools, the Transform Workforce Academy community can build a robust infrastructure that fosters a supportive and inclusive environment, providing employment opportunities and career development for individuals with criminal records.

**Comment by chintakjoshi** [comment] 2023-08-12 00:57
Building a thriving open-source community around a project requires a robust infrastructure that not only supports collaboration but also ensures that members feel valued, respected, and heard. Here's a foundational strategy to set the stage for a successful community:

1) Clear Vision and Mission Statement:

Priority: Clearly articulate the project's purpose, goals, and values.

Action Plan: Host brainstorming sessions with initial contributors to define the project's vision and mission. Once defined, prominently display this statement on the project's homepage and documentation.

Justification: A clear vision and mission give direction to the community and help align efforts.

2) Effective Collaboration Tools:

Priority: Ensure that contributors have the tools they need to collaborate efficiently.

Action Plan: Set up version control systems like Git, and platforms like GitHub or GitLab. Ensure that there's clear documentation on how to use these tools.

Justification: Efficient collaboration is the backbone of open-source projects.

3) Comprehensive Community Guidelines:

Priority: Establish a respectful and inclusive environment.

Action Plan: Draft a Code of Conduct, Contributing guidelines, and a LICENSE. Seek community feedback before finalizing and ensure they are easily accessible.

Justification: Clear guidelines ensure that all contributors understand their rights and responsibilities.

4) Robust Feedback Mechanism:

Priority: Allow community members to provide feedback easily.

Action Plan: Implement tools like issue trackers, forums, or feedback forms. Regularly review feedback and respond in a timely manner.

Justification: Feedback mechanisms ensure continuous improvement and show community members that their opinions are valued.

5) Open Communication Platforms:

Priority: Facilitate open and transparent communication.

Action Plan: Set up communication platforms like Slack, Discord, or mailing lists. Host regular community meetings or webinars.
Justification: Open communication fosters trust and ensures that all members are on the same page.

This revised plan provides a clear priority for each point, a concrete action plan, and a justification based on the sources you provided.

CITATIONS: 

https://www.cmsdrupal.com/blog/anatomy-great-open-source-documentation-how-document-your-projects-github

https://www.brookings.edu/articles/strengthening-digital-infrastructure-a-policy-agenda-for-free-and-open-source-software/

**Closed** 2023-08-22 17:28 UTC
